# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0c5625a4e95f1687d12683cdf179c3a1a09d0aa5780d180cd72423ac2ea80cb8ba05a2eed776d4d32940f65a11d29918dca7b70879dd72651cf2c13cd626070

test:
  secret_key_base: 33eb62a021edcb6a1c9bf684ddca77b3c95b0dfe5fc1a78fb73b3ea35153f99ac31d24cafb9df62dbd16ddb92c93533a4a27e1f1d1c160cb6425d7929730614a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
